#############################################################################
# Makefile for building: CSIM
<<<<<<< HEAD
# Generated by qmake (3.0) (Qt 5.5.0)
=======
# Generated by qmake (3.0) (Qt 5.6.0)
>>>>>>> 410fbe781a9665957377379831261e0feba8a3d0
# Project:  crowd.pro
# Template: app
# Command: D:\Qt\5.6\msvc2013_64\bin\qmake.exe -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile crowd.pro
#############################################################################

MAKEFILE      = Makefile

<<<<<<< HEAD
####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -I/usr/local/include/SDL2 -D_REENTRANT -std=c++11 -msse -msse2 -msse3 -march=native -g -std=c++11 -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/i7620560/NGL/include -Iinclude -I/opt/qt/5.5/gcc_64/include -I/opt/qt/5.5/gcc_64/include/QtOpenGL -I/opt/qt/5.5/gcc_64/include/QtWidgets -I/opt/qt/5.5/gcc_64/include/QtGui -I/opt/qt/5.5/gcc_64/include/QtCore -Imoc -I/opt/qt/5.5/gcc_64/mkspecs/linux-clang
QMAKE         = /opt/qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CSIM1.0.0
DISTDIR = /home/i7620560/Documents/programming/specialist/crowds/obj/CSIM1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/opt/qt/5.5/gcc_64 -Wl,-rpath,/home/i7620560/NGL/lib -Wl,-rpath,/opt/qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -L/home/i7620560/NGL/lib -l NGL -ltiff -L/opt/qt/5.5/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		src/AABB.cpp \
		src/actor.cpp \
		src/base.cpp \
		src/NGLScene.cpp \
		src/object.cpp \
		src/scene.cpp \
		src/shader.cpp \
		src/sim_time.cpp \
		src/util.cpp \
		src/vectors.cpp moc/moc_NGLScene.cpp
OBJECTS       = obj/main.o \
		obj/AABB.o \
		obj/actor.o \
		obj/base.o \
		obj/NGLScene.o \
		obj/object.o \
		obj/scene.o \
		obj/shader.o \
		obj/sim_time.o \
		obj/util.o \
		obj/vectors.o \
		obj/moc_NGLScene.o
DIST          = crowd.pro include/base.hpp \
		include/AABB.hpp \
		include/actor.hpp \
		include/base.hpp \
		include/NGLScene.hpp \
		include/object.hpp \
		include/scene.hpp \
		include/shader.hpp \
		include/sim_time.hpp \
		include/util.hpp \
		include/vectors.hpp main.cpp \
		src/AABB.cpp \
		src/actor.cpp \
		src/base.cpp \
		src/NGLScene.cpp \
		src/object.cpp \
		src/scene.cpp \
		src/shader.cpp \
		src/sim_time.cpp \
		src/util.cpp \
		src/vectors.cpp
QMAKE_TARGET  = CSIM
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = CSIM


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: crowd.pro ../.qmake.cache /opt/qt/5.5/gcc_64/mkspecs/linux-clang/qmake.conf /opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/clang.conf \
		/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/linux-clang/qmake.conf \
		/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../.qmake.cache \
		/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/home/i7620560/NGL/UseNGL.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/resources.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/moc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/uic.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf \
		crowd.pro \
		/opt/qt/5.5/gcc_64/lib/libQt5OpenGL.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Widgets.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-clang CONFIG+=debug -o Makefile crowd.pro
/opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/clang.conf:
/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/linux-clang/qmake.conf:
/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
../.qmake.cache:
/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
/home/i7620560/NGL/UseNGL.pri:
/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/qt.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/resources.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/moc.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/uic.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf:
crowd.pro:
/opt/qt/5.5/gcc_64/lib/libQt5OpenGL.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Widgets.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Gui.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Core.prl:
=======
first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:\Qt\5.6\msvc2013_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: crowd.pro .qmake.cache D:\Qt\5.6\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf D:\Qt\5.6\msvc2013_64\mkspecs\features\spec_pre.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\common\angle.conf \
		D:\Qt\5.6\msvc2013_64\mkspecs\common\msvc-base.conf \
		D:\Qt\5.6\msvc2013_64\mkspecs\common\msvc-desktop.conf \
		D:\Qt\5.6\msvc2013_64\mkspecs\qconfig.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dcore.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dinput.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquick.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3drender.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_dbus.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_labscontrols_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_labstemplates_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_location.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_script.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialbus.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webview.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\qt_functions.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\qt_config.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\qt_config.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\spec_post.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\exclusive_builds.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\default_pre.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\default_pre.prf \
		\NGL\UseNGL.pri \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\resolve_config.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\exclusive_builds_post.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\default_post.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\console.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\qml_debug.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\rtti.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\precompile_header.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\warn_on.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\qt.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\resources.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\moc.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\opengl.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\uic.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\testcase_targets.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\exceptions.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\yacc.prf \
		D:\Qt\5.6\msvc2013_64\mkspecs\features\lex.prf \
		crowd.pro \
		D:\Qt\5.6\msvc2013_64\lib\Qt5OpenGL.prl \
		D:\Qt\5.6\msvc2013_64\lib\Qt5Widgets.prl \
		D:\Qt\5.6\msvc2013_64\lib\Qt5Gui.prl \
		D:\Qt\5.6\msvc2013_64\lib\Qt5Core.prl
	$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile crowd.pro
D:\Qt\5.6\msvc2013_64\mkspecs\features\spec_pre.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\common\angle.conf:
D:\Qt\5.6\msvc2013_64\mkspecs\common\msvc-base.conf:
D:\Qt\5.6\msvc2013_64\mkspecs\common\msvc-desktop.conf:
D:\Qt\5.6\msvc2013_64\mkspecs\qconfig.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dcore.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dinput.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dlogic.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquick.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3drender.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_3drender_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_core.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_dbus.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_dbus_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_help.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_labscontrols_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_labstemplates_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_location.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_network.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_script.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialbus.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialbus_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webview.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\modules\qt_lib_zlib_private.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\features\qt_functions.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\qt_config.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\qt_config.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\spec_post.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\exclusive_builds.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\default_pre.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\default_pre.prf:
\NGL\UseNGL.pri:
D:\Qt\5.6\msvc2013_64\mkspecs\features\resolve_config.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\default_post.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\console.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\qml_debug.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\rtti.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\precompile_header.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\warn_on.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\qt.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\resources.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\moc.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\win32\opengl.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\uic.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\testcase_targets.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\exceptions.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\yacc.prf:
D:\Qt\5.6\msvc2013_64\mkspecs\features\lex.prf:
crowd.pro:
D:\Qt\5.6\msvc2013_64\lib\Qt5OpenGL.prl:
D:\Qt\5.6\msvc2013_64\lib\Qt5Widgets.prl:
D:\Qt\5.6\msvc2013_64\lib\Qt5Gui.prl:
D:\Qt\5.6\msvc2013_64\lib\Qt5Core.prl:
>>>>>>> 410fbe781a9665957377379831261e0feba8a3d0
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile crowd.pro

qmake_all: FORCE

<<<<<<< HEAD

all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/base.hpp include/AABB.hpp include/actor.hpp include/base.hpp include/NGLScene.hpp include/object.hpp include/scene.hpp include/shader.hpp include/sim_time.hpp include/util.hpp include/vectors.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp src/AABB.cpp src/actor.cpp src/base.cpp src/NGLScene.cpp src/object.cpp src/scene.cpp src/shader.cpp src/sim_time.cpp src/util.cpp src/vectors.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
=======
make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) CSIM.exp
	-$(DEL_FILE) CSIM.ilk
	-$(DEL_FILE) CSIM.idb
distclean: debug-distclean release-distclean  FORCE
>>>>>>> 410fbe781a9665957377379831261e0feba8a3d0
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) CSIM.lib CSIM.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
<<<<<<< HEAD

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc/moc_NGLScene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_NGLScene.cpp
moc/moc_NGLScene.cpp: /home/i7620560/NGL/include/ngl/Camera.h \
		/home/i7620560/NGL/include/ngl/Types.h \
		/home/i7620560/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7620560/NGL/include/ngl/Vec4.h \
		/home/i7620560/NGL/include/ngl/Vec2.h \
		/home/i7620560/NGL/include/ngl/Vec3.h \
		/home/i7620560/NGL/include/ngl/Mat4.h \
		/home/i7620560/NGL/include/ngl/RibExport.h \
		/home/i7620560/NGL/include/ngl/Plane.h \
		/home/i7620560/NGL/include/ngl/AABB.h \
		/home/i7620560/NGL/include/ngl/BBox.h \
		/home/i7620560/NGL/include/ngl/VertexArrayObject.h \
		/home/i7620560/NGL/include/ngl/Colour.h \
		/home/i7620560/NGL/include/ngl/Light.h \
		/home/i7620560/NGL/include/ngl/Text.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglwindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDeviceWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindow.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QObject \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtCore/QMargins \
		/opt/qt/5.5/gcc_64/include/QtCore/QRect \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurface.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDevice \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLContext \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QImage \
		include/NGLScene.hpp
	/opt/qt/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt/5.5/gcc_64/mkspecs/linux-clang -I/home/i7620560/Documents/programming/specialist/crowds -I/home/i7620560/NGL/include -I/home/i7620560/Documents/programming/specialist/crowds/include -I/opt/qt/5.5/gcc_64/include -I/opt/qt/5.5/gcc_64/include/QtOpenGL -I/opt/qt/5.5/gcc_64/include/QtWidgets -I/opt/qt/5.5/gcc_64/include/QtGui -I/opt/qt/5.5/gcc_64/include/QtCore include/NGLScene.hpp -o moc/moc_NGLScene.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/main.o: main.cpp /opt/qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		include/NGLScene.hpp \
		/home/i7620560/NGL/include/ngl/Camera.h \
		/home/i7620560/NGL/include/ngl/Types.h \
		/home/i7620560/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7620560/NGL/include/ngl/Vec4.h \
		/home/i7620560/NGL/include/ngl/Vec2.h \
		/home/i7620560/NGL/include/ngl/Vec3.h \
		/home/i7620560/NGL/include/ngl/Mat4.h \
		/home/i7620560/NGL/include/ngl/RibExport.h \
		/home/i7620560/NGL/include/ngl/Plane.h \
		/home/i7620560/NGL/include/ngl/AABB.h \
		/home/i7620560/NGL/include/ngl/BBox.h \
		/home/i7620560/NGL/include/ngl/VertexArrayObject.h \
		/home/i7620560/NGL/include/ngl/Colour.h \
		/home/i7620560/NGL/include/ngl/Light.h \
		/home/i7620560/NGL/include/ngl/Text.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglwindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDeviceWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindow.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QObject \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtCore/QMargins \
		/opt/qt/5.5/gcc_64/include/QtCore/QRect \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurface.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDevice \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLContext \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QImage
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/AABB.o: src/AABB.cpp include/AABB.hpp \
		include/vectors.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/AABB.o src/AABB.cpp

obj/actor.o: src/actor.cpp include/actor.hpp \
		include/vectors.hpp \
		include/base.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/actor.o src/actor.cpp

obj/base.o: src/base.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/base.o src/base.cpp

obj/NGLScene.o: src/NGLScene.cpp /opt/qt/5.5/gcc_64/include/QtGui/QMouseEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		include/NGLScene.hpp \
		/home/i7620560/NGL/include/ngl/Camera.h \
		/home/i7620560/NGL/include/ngl/Types.h \
		/home/i7620560/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/i7620560/NGL/include/ngl/Vec4.h \
		/home/i7620560/NGL/include/ngl/Vec2.h \
		/home/i7620560/NGL/include/ngl/Vec3.h \
		/home/i7620560/NGL/include/ngl/Mat4.h \
		/home/i7620560/NGL/include/ngl/RibExport.h \
		/home/i7620560/NGL/include/ngl/Plane.h \
		/home/i7620560/NGL/include/ngl/AABB.h \
		/home/i7620560/NGL/include/ngl/BBox.h \
		/home/i7620560/NGL/include/ngl/VertexArrayObject.h \
		/home/i7620560/NGL/include/ngl/Colour.h \
		/home/i7620560/NGL/include/ngl/Light.h \
		/home/i7620560/NGL/include/ngl/Text.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglwindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDeviceWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QWindow \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindow.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QObject \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtCore/QMargins \
		/opt/qt/5.5/gcc_64/include/QtCore/QRect \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurface.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QPaintDevice \
		/opt/qt/5.5/gcc_64/include/QtGui/QOpenGLContext \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QImage \
		/home/i7620560/NGL/include/ngl/Material.h \
		/home/i7620560/NGL/include/ngl/NGLInit.h \
		/home/i7620560/NGL/include/ngl/Singleton.h \
		/home/i7620560/NGL/include/ngl/VAOPrimitives.h \
		/home/i7620560/NGL/include/ngl/ShaderLib.h \
		/home/i7620560/NGL/include/ngl/Shader.h \
		/home/i7620560/NGL/include/ngl/ShaderProgram.h \
		/home/i7620560/NGL/include/ngl/Util.h \
		/home/i7620560/NGL/include/ngl/Mat3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/object.o: src/object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/object.o src/object.cpp

obj/scene.o: src/scene.cpp include/scene.hpp \
		include/actor.hpp \
		include/vectors.hpp \
		include/base.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/scene.o src/scene.cpp

obj/shader.o: src/shader.cpp include/shader.hpp \
		/home/i7620560/NGL/include/ngl/Types.h \
		/home/i7620560/NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/shader.o src/shader.cpp

obj/sim_time.o: src/sim_time.cpp include/sim_time.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sim_time.o src/sim_time.cpp

obj/util.o: src/util.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/util.o src/util.cpp

obj/vectors.o: src/vectors.cpp include/vectors.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vectors.o src/vectors.cpp

obj/moc_NGLScene.o: moc/moc_NGLScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_NGLScene.o moc/moc_NGLScene.cpp

####### Install

install:  FORCE

uninstall:  FORCE

=======
>>>>>>> 410fbe781a9665957377379831261e0feba8a3d0
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
